let preamble = 'We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defense, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America.';
let article1 = 'Legislative Branch: the U.S. Congress makes the laws for the United States. Congress has two parts, called "Houses," the House of Representatives and the Senate.';
let article2 = 'Executive Branch: the President, Vice-President, Cabinet, and Departments under the Cabinet Secretaries carry out the laws made by Congress.';
let article3 = 'Judicial Branch: the Supreme Court decides court cases according to US Constitution. The courts under the Supreme Court decide criminal and civil court cases according to the correct federal, state, and local laws.';
let article4 = 'States\' powers: States have the power to make and carry out their own laws. State laws that are related to the people and problems of their area. States respect other states laws and work together with other states to fix regional problems.';
let article5 = 'Amendments: The Constitution can be changed. New amendments can be added to the US Constitution with the approval by a two-thirds vote in each house of Congress (67, 281) and three-fourth vote by the states.';
let article6 = 'Federal powers: The Constitution and federal laws are higher than state and local laws. All laws must agree with the US Constitution.';
let article7 = 'Ratification: The Constitution was presented to George Washington and the men at the Constitutional Convention on September 17, 1787, Representatives from twelve out of the thirteen original states signed the Constitution. From September 1787 to July 1788, the states meet, talked about, and finally voted to approve the Constitution. ';

console.log("Preamble to the Constitution: \n" + preamble);
console.log("-------------------------------");
console.log(article1);
console.log("");
console.log(article2);
console.log("");
console.log(article3);
console.log("");
console.log(article4);
console.log("");
console.log(article5);
console.log("");
console.log(article6);
console.log("");
console.log(article7);
console.log("");
